[general]
# The user agent is a string that helps identify this application to NationStates.
# Place your main nation's name here
user_agent = '<Your nation name here>'

[puppets]
[puppets.default]
nation_names = ['nation1', 'nation2', 'nation3']
password = 'hunterprime'

# Get nation names from a text file instead.
# If this is used, the nation_names config above is ignored.
# The file lists each nation name on each line.
# nation_name_file = ''

# New settings to apply to these puppets. (See [link] to know how to use)
# new_settings = {}